export const categorizedHobbies = {
    art_creativity: [
        "music",
        "painting",
        "writing",
        "dance",
        "photography",
        "film",
        "architecture",
    ],
    sports_activity: [
        "football",
        "basketball",
        "fitness",
        "cycling",
        "swimming",
        "skiing",
        "yoga",
        "hiking",
    ],
    life_culture: [
        "language_learning",
        "reading",
        "travel",
        "cooking",
        "coffee_culture",
        "theater",
    ],
    technology_games: [
        "gaming",
        "coding",
        "ai",
        "puzzles",
        "social_media",
    ],
    social_daily: [
        "meeting_people",
        "animals",
        "fashion",
        "nature",
        "sports_fitness",
    ],
};
